# Generated by Django 3.2 on 2021-04-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20210429_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='Type',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='PA',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='desigination',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='joining',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='leave',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='timein',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='timeout',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='workingHour',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='fullname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
