# Generated by Django 3.2 on 2021-05-16 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendence', '0003_auto_20210430_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=7)),
                ('fullname', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('PAL', models.CharField(max_length=10)),
                ('timein', models.CharField(max_length=10)),
                ('timeout', models.CharField(max_length=10)),
                ('workinghour', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
