# Generated by Django 3.2 on 2021-05-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_auto_20210516_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='timein',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='timeout',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='workinghour',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
