# Generated by Django 3.2 on 2021-05-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_auto_20210516_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='emp_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
